name: Deploy Supabase Functions and Migrations

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: tu-id-de-proyecto

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy Supabase Functions
        run: |
          supabase functions deploy --project-ref $PROJECT_ID

      - name: Apply Supabase Database Migrations
        run: |
          supabase db push --project-ref $PROJECT_ID
